create table if not exists ticket (
                                      id bigint generated by default as identity,
                                      body varchar(255),
    name varchar(255),
    subject varchar(255),
    primary key (id)
    );
create table if not exists attachment (
                                          id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    ticket_id bigint,
    primary key (id),
    foreign key (ticket_id) references ticket
    );

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
                                     username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    PRIMARY KEY (username)
    );
CREATE TABLE IF NOT EXISTS user_roles (
                                          user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
                                          username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
    );

create table if not exists comment (
                                       id bigint generated by default as identity,
                                       content varchar(1000),
    author varchar(255),
    created_at timestamp,
    ticket_id bigint,
    primary key (id),
    foreign key (ticket_id) references ticket
    );

create table if not exists poll (
                                    id bigint generated by default as identity,
                                    question varchar(255),
                                    primary key (id)
);

create table if not exists poll_options (
                                            poll_id bigint not null,
                                            options varchar(255),
                                            foreign key (poll_id) references poll
);

create table if not exists vote (
                                    id bigint generated by default as identity,
                                    selected_option integer not null,
                                    username varchar(255),
                                    poll_id bigint,
                                    primary key (id),
                                    foreign key (poll_id) references poll
);

create table if not exists poll_comment (
                                            id bigint generated by default as identity,
                                            author varchar(255),
                                            content varchar(1000),
                                            created_at timestamp,
                                            poll_id bigint,
                                            primary key (id),
                                            foreign key (poll_id) references poll
);